problem:
  number: 1
  title: "Two Sum"
  leetcode_url: "https://leetcode.com/problems/two-sum/"
  difficulty: "easy"
  tags: ["Arrays & Hashing"]

solutions:
  python: "problems/two_sum/two_sum.py"
  cpp: "problems/two_sum/two_sum.cc"

complexity:
  time: "O(n)"
  space: "O(n)"

notes: ""
readme_link: ""
