name: Cpp Format & Test

on: [push]

jobs:
  build-cpp:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake build-essential
          # Install Google Test from source - most reliable approach
          git clone https://github.com/google/googletest.git --depth 1
          cd googletest
          mkdir build && cd build
          cmake .. -DCMAKE_INSTALL_PREFIX=/usr/local -DBUILD_SHARED_LIBS=ON
          make -j$(nproc)
          sudo make install
          sudo ldconfig

      - name: Debug Google Test configuration
        run: make debug-gtest

      - name: Format C++ code
        run: make format-cpp

      - name: Lint C++ code
        run: make lint-cpp

      - name: Run C++ tests
        run: make test-cpp:all

      - name: Clean
        run: make clean
