---
name: Python Linter

on: # yamllint disable-line rule:truthy
  push:
    branches: ["main"]

jobs:
  lint-python:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Lint Python code using Makefile
        run: |
          make lint-python

      - name: Format check Python code using Makefile
        run: |
          make format-python
          # Check if any files were modified by formatting
          if ! git diff --exit-code; then
            echo "Code formatting issues found. Please run 'make \
            format-python' locally."
            exit 1
          fi
