---
name: Postsubmit (C++)

on: # yamllint disable-line rule:truthy
  push:
    branches: ["main"]

jobs:
  test-cpp:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake build-essential

      - name: Install Google Test
        run: |
          # Install Google Test from source - most reliable approach
          git clone https://github.com/google/googletest.git --depth 1
          cd googletest
          mkdir build && cd build
          cmake .. -DCMAKE_INSTALL_PREFIX=/usr/local -DBUILD_SHARED_LIBS=ON
          make -j$(nproc)
          sudo make install
          sudo ldconfig

      - name: Debug Google Test configuration
        run: make debug-gtest

      - name: Run all C++ tests using Makefile
        run: |
          make test-cpp:all

      - name: Show project statistics
        run: |
          make stats
