---
name: PR Size Labeler

on: # yamllint disable-line rule:truthy
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  size-label:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Label PR based on size
        uses: codelytv/pr-size-labeler@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          xs_label: "size/XS"
          xs_max_size: 10
          s_label: "size/S"
          s_max_size: 30
          m_label: "size/M"
          m_max_size: 100
          l_label: "size/L"
          l_max_size: 500
          xl_label: "size/XL"
          fail_if_xl: false
          message_if_xl: >
            This PR is very large. Consider breaking it down into smaller PRs
            for easier review and better maintainability.
          files_to_ignore: |
            package-lock.json
            yarn.lock
            pnpm-lock.yaml
            Cargo.lock
            composer.lock
            Pipfile.lock
            poetry.lock
            *.min.js
            *.min.css
            *.map
            dist/*
            build/*
            __pycache__/*
            *.pyc
