name: Python Lint & Test

on: [push]

jobs:
  build-python:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Format Python code
        run: make format-python

      - name: Lint Python code
        run: make lint-python

      - name: Run Python tests
        run: make test-py:all
